# this is a template for the config file
# demonstrating some of the common options used in cpg-flow
[workflow]


name = 'rdrnaseq'

# mandatory fields for cpg-flow, not populated by analysis-runner

sequencing_type = 'genome'

# used to make sure we don't repeat previously completed stages
check_expected_outputs = true

# the method to register outputs, can be missing - will not generate metamist analysis entries
status_reporter = 'metamist'
